apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add-task-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: addtask.copcare.shop
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: add-task-svc
            port: 
              number: 80
